# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2017-05-23 18:09
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('countryinfo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, unique=True)),
                ('email', models.CharField(max_length=50, unique=True)),
                ('profile_photo', models.ImageField(blank=True, null=True, upload_to='')),
                ('password', models.CharField(blank=True, max_length=30, null=True)),
                ('email_verified', models.BooleanField(default=False)),
                ('added_on', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_on', models.DateTimeField(default=datetime.datetime.now)),
                ('is_active', models.BooleanField(default=True)),
                ('address', models.ManyToManyField(to='countryinfo.Address')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='countryinfo.Country')),
            ],
            options={
                'db_table': 'customer_tbl',
            },
        ),
        migrations.CreateModel(
            name='ServiceRegistration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service_user', models.BooleanField(default=False)),
                ('service_provider', models.BooleanField(default=False)),
                ('user_service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'service_registered',
            },
        ),
    ]
